[build]
  command = "npm run build"
  publish="/build'
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
    from = "/api/*"
    to = "http://193.140.134.43/tomcat/platesapi/api/v1/:splat"
    status = 200
    force = true
