export { default as authService } from "./auth-service";
export { default as trainerService } from "./trainer-service";
export { default as companyService } from "./company-service";
export { default as companyAdminService } from "./company-admin-service";
export { default as branchService } from "./branch-service";
export { default as branchAdminService } from "./branch-admin-service";
export { default as userService } from "./user-service";
export { default as reportService } from "./report-service";
export { default as imageService } from "./image-service";